services:
  backend-service:
    image: backend-service
    build:
      context: .
      dockerfile: Backend-Service/Dockerfile
      
  postgresDb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/PostgresData:/var/lib/postgresql/data

